project:
  type: website
  output-dir: docs


website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Labs
      - href: labs.qmd
        text: Labs

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



